# Generated by Django 5.0.6 on 2024-10-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkEntry',
            new_name='log',
        ),
    ]
